name: Build & Push Manually API

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module API'
        required: true
        default: 'warning'
        type: choice
        options:
        - api-show-service
        - api-lofselectclub-service
            
env:
  module: ${{ inputs.module }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Push Manually ${{ inputs.module }}
    env:
      MVN: mvn --show-version --batch-mode

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Get Build image name & SHA_SHORT
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=buildimage::$(echo anthonydenecheau/"${{ inputs.module }}" | sed -r 's/api/scc/g')"

    - name: Cache maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 
          
    - name: Build with Maven
      run: mvn --projects ${{env.module}} clean package docker:build
      env:
        BUILD_NAME: ${{ steps.vars.outputs.sha_short }}   


    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN}}
        
    - name: Docker push
      run: |
        docker push ${{ steps.vars.outputs.buildimage }}:${{ steps.vars.outputs.sha_short }}

    # https://github.com/marketplace/actions/microsoft-teams-notification
    - name: Notify dedicated teams channel
      if: success()
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "&#x2705; Docker image: ${{ steps.vars.outputs.buildimage }}:${{ steps.vars.outputs.sha_short }}" 
        notification-color: 28a745
        timezone: Europe/Paris         
